# Original data
data = {
    "PRODUCT NAME": {
        "0": "Ageratum",
        "1": "Alyssum",
        "2": "Bacopa",
        "3": "Begonia",
        "4": "Bidens",
        "5": "Bridal Veil",
        "6": "Calibrachoa",
        "7": "Canna",
        "8": "Celosia",
        "9": "Cleome",
        "10": "Coleus",
        "11": "Cosmos",
        "12": "Cuphea",
        "13": "Dahlia",
        "14": "Dianthus",
        "15": "Dichondra",
        "16": "Dusty Miller",
        "17": "Fuchsia",
        "18": "Fuseable",
        "19": "Gazania",
        "20": "Geranium",
        "21": "Gerbera",
        "22": "Gomphrena",
        "23": "Grandaisy",
        "24": "Impatiens",
        "25": "Ipomoea/Sweet Potato Vine",
        "26": "Kwik Kombos",
        "27": "Lantana",
        "28": "Lobelia",
        "29": "Marigold",
        "30": "Melampodium",
        "31": "Mimulus",
        "32": "Nasturtium",
        "33": "Nemesia",
        "34": "Nicotiana",
        "35": "Ornamental Oregano",
        "36": "Osteospermum",
        "37": "Pansy",
        "38": "Pentas",
        "39": "Petunia",
        "40": "Phlox",
        "41": "Portulaca",
        "42": "Ptilotus",
        "43": "Salvia",
        "44": "Senecio",
        "45": "Snapdragon",
        "46": "Spikes",
        "47": "Stock",
        "48": "Sunflower",
        "49": "Supertunia/ PW",
        "50": "Thunbergia",
        "51": "Torenia",
        "52": "Trixi Combos",
        "53": "Verbena",
        "54": "Vinca Vine",
        "55": "Zinnia"
    },
    "DESCRIPTION": {
        "0": "Mounding 8\"-12\"",
        "1": "Mounding 6\" - 10\"",
        "2": "Trailing 18\"-24\"",
        "3": "Upright and Trailing",
        "4": "Mounding 12\"-16\"",
        "5": "Trailing 12\"-18\"",
        "6": "Mounding/Semi-Trailing",
        "7": "Upright 30\"-48\"",
        "8": "Upright 6\"-40\"",
        "9": "Upright 36\"-44\"",
        "10": "Mounding 8\"-18\"",
        "11": "Upright 12\"-48\"",
        "12": "Mounding 10\"-24\"",
        "13": "Upright/Mounding 8\"-22\"",
        "14": "Upright 8\"-10\"",
        "15": "Trailing 40\"-60\"",
        "16": "Mounding",
        "17": "Upright and Trailing",
        "18": "Petunia/Bacopa mix- Mounding",
        "19": "Upright 8\"-10\"",
        "20": "Upright 12\" -22\"",
        "21": "Mounding/ Large blooms",
        "22": "Upright 36\"-48\"",
        "23": "Mounding18\"-24\"",
        "24": "Mounding 10\"-28\"",
        "25": "Trailing 4'-15'",
        "26": "Mounding 12\"-18\"",
        "27": "Mounding/Semi-Trailing",
        "28": "Mounding 6\"- 12\"",
        "29": "Mounding 10\"-36\"",
        "30": "Mounding 6\"-12\"",
        "31": "Trailing",
        "32": "Upright and Trailing",
        "33": "Mounding 12\"-14\"",
        "34": "Mounding 16\"20\"",
        "35": "Trailing 12'-16'",
        "36": "Mounding 6\"-24\"",
        "37": "Upright and Trailing",
        "38": "Mounding 24\"-36\"",
        "39": "Mounding/Tailing",
        "40": "Mounding 14\"-16\"",
        "41": "Trailing 8\"-15\"",
        "42": "Mounding 12\"-22\"",
        "43": "Upright 15\"-20\"",
        "44": "Mounding 10\"-16\"",
        "45": "Mounding 6\"-12\"",
        "46": "Upright 24\"-36\"",
        "47": "Mounding 15\"-18\"",
        "48": "Upright Dwarf 12\"-15\"",
        "49": "Mounding/Tailing",
        "50": "Climbing Vine 72\"-96\"",
        "51": "Mounding 8\"",
        "52": "Mounding 12\"-18\"",
        "53": "Upright and Trailing",
        "54": "Trailing 8\"-15\"",
        "55": "Mounding 6\"-40\""
    },
    "COLOR": {
        "0": "Blue, Purple, Pink",
        "1": "Assorted colors",
        "2": "Blue, pink, white",
        "3": "Red, Pink, Yellow,",
        "4": "Assorted colors",
        "5": "Purple/White",
        "6": "Assorted colors",
        "7": "Assorted colors",
        "8": "Assorted colors",
        "9": "Assorted colors",
        "10": "Assorted colors",
        "11": "Assorted colors",
        "12": "Assorted colors",
        "13": "Assorted colors",
        "14": "Assorted colors",
        "15": "Silver/Green",
        "16": "Silver/Green",
        "17": "Assorted colors",
        "18": "Assorted colors",
        "19": "Assorted colors",
        "20": "Red, White, Pink, Orange",
        "21": "Assorted colors",
        "22": "Assorted colors",
        "23": "Assorted colors",
        "24": "Assorted colors",
        "25": "Purple/Green",
        "26": "Assorted colors",
        "27": "Assorted colors",
        "28": "Blue.Purple, White",
        "29": "Assorted colors",
        "30": "Golden",
        "31": "Mulitcolor",
        "32": "Assorted colors",
        "33": "Assorted colors",
        "34": "Purple",
        "35": "Shades of purple",
        "36": "Assorted colors",
        "37": "Assorted colors",
        "38": "Assorted colors",
        "39": "Assorted colors",
        "40": "Assorted colors",
        "41": "Assorted colors",
        "42": "Purple/Pink shades",
        "43": "Assorted colors",
        "44": "Silver",
        "45": "Assorted colors",
        "46": "Green/Brown",
        "47": "Assorted colors",
        "48": "Yellow",
        "49": "Assorted colors",
        "50": "Assorted colors",
        "51": "Assorted colors",
        "52": "Assorted colors",
        "53": "Assorted colors",
        "54": "Variegated",
        "55": "Assorted colors"
    },
    "LIGHT REQUIREMENT": {
        "0": "Sun to Shade",
        "1": "Sun",
        "2": "Sun",
        "3": "Sun to Shade",
        "4": "Sun",
        "5": "Sun to Shade",
        "6": "Sun",
        "7": "Sun",
        "8": "Sun",
        "9": "Sun",
        "10": "Sun to Shade",
        "11": "Sun",
        "12": "Sun",
        "13": "Sun",
        "14": "Sun",
        "15": "Sun to Shade",
        "16": "Sun to Shade",
        "17": "Sun to Shade",
        "18": "Sun",
        "19": "Sun",
        "20": "Sun",
        "21": "Sun",
        "22": "Sun",
        "23": "Sun",
        "24": "Sun to Shade",
        "25": "Sun to Shade",
        "26": "Sun",
        "27": "Sun",
        "28": "Sun",
        "29": "Sun",
        "30": "Sun",
        "31": "Sun",
        "32": "Sun",
        "33": "Sun to Shade",
        "34": "Sun to Shade",
        "35": "Sun",
        "36": "Sun",
        "37": "Sun to Shade",
        "38": "Sun",
        "39": "Sun",
        "40": "Sun to Shade",
        "41": "Sun",
        "42": "Sun",
        "43": "Sun",
        "44": "Sun",
        "45": "Sun",
        "46": "Sun",
        "47": "Sun",
        "48": "Sun",
        "49": "Sun",
        "50": "Sun",
        "51": "Assorted colors",
        "52": "Sun",
        "53": "Sun",
        "54": "Sun to Shade",
        "55": "Sun"
    }
}

# Initialize an empty list to hold the new structure
products = []

# Get the keys (indices) from the "PRODUCT NAME" dictionary
indices = data["PRODUCT NAME"].keys()

# Loop through the indices and construct the new product structure
for idx in indices:
    product = {
        "title": data["PRODUCT NAME"][idx],
        "description": data["DESCRIPTION"][idx],
        "color": data["COLOR"][idx],
        "lightRequirement": data["LIGHT REQUIREMENT"][idx]
    }
    products.append(product)

# Print the transformed structure without quotes around keys
print("[")
for product in products:
    print("  {")
    print(f"    title: '{product['title']}',")
    print(f"    description: '{product['description']}',")
    print(f"    color: '{product['color']}',")
    print(f"     className:'griditem',")
    print(f"    lightRequirement: '{product['lightRequirement']}'")

    print("  },")
print("]")