[
    {
      type: 'Flowering Shrubs',
      title: 'Almond, Pink Flowering',
      description: 'Double pink flowers in early spring.',
       className:'griditem',
    },
    {
      type: 'Flowering Shrubs',
      title: 'Althea, Lil' Kim Red',
      description: 'Carmine-red blooms.',
       className:'griditem',
    },
    {
      type: 'Flowering Shrubs',
      title: 'Althea, Magenta Chiffon',
      description: 'Magenta-purple powderpuff blooms.',
       className:'griditem',
    },
    {
      type: 'Ornamental\/Shade Trees',
      title: 'Althea, Magenta Chiffon Tree',
      description: 'Magenta-purple powderpuff blooms; tree form.',
       className:'griditem',
    },
    {
      type: 'Fruit Trees',
      title: 'Apple, Braeburn',
      description: 'Medium to large fruits are green-striped with dark red.',
       className:'griditem',
    },
    {
      type: 'Fruit Trees',
      title: 'Apple, Cortland',
      description: 'Bears heavy crops of large red-striped fruit with white flesh.',
       className:'griditem',
    },
    {
      type: 'Fruit Trees',
      title: 'Apple, Empire',
      description: 'Medium sized dark red, striped fruit.',
       className:'griditem',
    },
    {
      type: 'Fruit Trees',
      title: 'Apple, Fuji',
      description: 'Medium sized fruits are reddish-green in color.',
       className:'griditem',
    },
    {
      type: 'Fruit Trees',
      title: 'Apple, Gala',
      description: 'Medium sized fruits have golden-yellow skin with reddish blush.',
       className:'griditem',
    },
    {
      type: 'Fruit Trees',
      title: 'Apple, Granny Smith',
      description: 'Large, waxy, smooth green skin with small white lenticels.',
       className:'griditem',
    },
    {
      type: 'Fruit Trees',
      title: 'Apple, Honeycrisp',
      description: 'Very large fruits are scarlet-red over a yellow background.',
       className:'griditem',
    },
    {
      type: 'Fruit Trees',
      title: 'Apple, Honeygold',
      description: 'Golden with red blush, very sweet.',
       className:'griditem',
    },
    {
      type: 'Fruit Trees',
      title: 'Apple, McIntosh',
      description: 'Medium to large, nearly round fruit with bright red skin.',
       className:'griditem',
    },
    {
      type: 'Fruit Trees',
      title: 'Apple, Pink Lady',
      description: 'Attractive pink blush over a yellow undertone.',
       className:'griditem',
    },
    {
      type: 'Fruit Trees',
      title: 'Apple, Red Delicious',
      description: 'Medium to large with red to striped skin.',
       className:'griditem',
    },
    {
      type: 'Fruit Trees',
      title: 'Apple, State Fair',
      description: 'Medium-sized fruit striped with reddish-orange over a yellow background.',
       className:'griditem',
    },
    {
      type: 'Fruit Trees',
      title: 'Apple, Wealthy',
      description: 'Large red-skinned fruit with white pink-veined flesh.',
       className:'griditem',
    },
    {
      type: 'Fruit Trees',
      title: 'Apple, Wolf River',
      description: 'Pale yellow skin with a dull red blush on enormous fruit.',
       className:'griditem',
    },
    {
      type: 'Fruit Trees',
      title: 'Apple, Yellow Delicious',
      description: 'Large with clear yellow skin, similar in shape to 'Red Delicious'.',
       className:'griditem',
    },
    {
      type: 'Fruit Trees',
      title: 'Apple, Zestar',
      description: 'Mostly red, crisp, with sweet and tart taste.',
       className:'griditem',
    },
    {
      type: 'Fruit Trees',
      title: 'Apricot, Chinese Mormon',
      description: 'Medium sized fruit with yellow to medium orange color and a red blush.',
       className:'griditem',
    },
    {
      type: 'Fruit Trees',
      title: 'Apricot, Moorpark',
      description: 'Juicy, sweet fruit. Good for fresh eating, drying or canning.',
       className:'griditem',
    },
    {
      type: 'Perennials',
      title: 'Astilbe, Dark Side of the Moon',
      description: 'Dark Chocolate-burgundy foliage, rosy purple flowers.',
       className:'griditem',
    },
    {
      type: 'Perennials',
      title: 'Astilbe, Visions In Red',
      description: 'Deep red buds open to pinkish-red flowers on full plumes.',
       className:'griditem',
    },
    {
      type: 'Flowering Shrubs',
      title: 'Azalea, Mandarin Lights',
      description: 'Orange flowers.',
       className:'griditem',
    },
    {
      type: 'Flowering Shrubs',
      title: 'Balloon Flower, Sentimental Blue',
      description: 'Balloon-shaped buds that open to saucer-like blue flowers.',
       className:'griditem',
    },
    {
      type: 'Flowering Shrubs',
      title: 'Barberry, Rose Glow',
      description: 'New foliage is pink with splash of cream 4' height.',
       className:'griditem',
    },
    {
      type: 'Flowering Shrubs',
      title: 'Barberry, Sunjoy Orange Pillar',
      description: 'Vivid orange foliage, narrow growth habit.',
       className:'griditem',
    },
    {
      type: 'Flowering Shrubs',
      title: 'Barberry, Sunjoy Sequins',
      description: 'Colorful new growth variegation of white, pink and mint green.',
       className:'griditem',
    },
    {
      type: 'Perennials',
      title: 'Bellflower, Dickson's Gold',
      description: 'Golden-yellow foliage. Blue flowers.',
       className:'griditem',
    },
    {
      type: 'Ornamental\/Shade Trees',
      title: 'Birch, Whitespire Clump',
      description: 'Borer resistant white birch with a pyramidal growth habit.',
       className:'griditem',
    },
    {
      type: 'Perennials',
      title: 'Brunnera, Jack Frost',
      description: 'Dark green foliage heavily frosted with silver.',
       className:'griditem',
    },
    {
      type: 'Flowering Shrubs',
      title: 'Burning Bush, Dwarf',
      description: 'Rounded plant with purple-red fall color and corky bark.',
       className:'griditem',
    },
    {
      type: 'Flowering Shrubs',
      title: 'Butterfly Bush, Lo & Behold Pink Micro Chip',
      description: 'Dwarf form with orchid pink blooms.',
       className:'griditem',
    },
    {
      type: 'Flowering Shrubs',
      title: 'Butterfly Bush, Miss Violet',
      description: 'Violet flower.',
       className:'griditem',
    },
    {
      type: 'Flowering Shrubs',
      title: 'Butterfly Bush, Royal Red',
      description: 'Purple red flowers.',
       className:'griditem',
    },
    {
      type: 'Flowering Shrubs',
      title: 'Buttonbush, Sugar Shack',
      description: 'Red fruit, glossy red tip foliage native.',
       className:'griditem',
    },
    {
      type: 'Perennials',
      title: 'Catmint, Junior Walker's Low',
      description: 'Compact 15-18in plants, blue flowers May thru September.',
       className:'griditem',
    },
    {
      type: 'Fruit Trees',
      title: 'Cherry, Montmorency',
      description: 'Fruit is large with brilliant red skin and firm yellow flesh.',
       className:'griditem',
    },
    {
      type: 'Fruit Trees',
      title: 'Cherry, North Star',
      description: 'A genetic dwarf, excellent for the home garden.',
       className:'griditem',
    },
    {
      type: 'Ornamental\/Shade Trees',
      title: 'Cherry, Pink Weeping (3' Graft)',
      description: 'Showy double pink flowers, low-grafted at about 3'.',
       className:'griditem',
    },
    {
      type: 'Ornamental\/Shade Trees',
      title: 'Cherry, Pink Weeping (6' Graft)',
      description: 'Showy double pink flowers, high-grafted at about 6'.',
       className:'griditem',
    },
    {
      type: 'Flowering Shrubs',
      title: 'Chokeberry, Low Scape Mound',
      description: 'Stays 2' tall and wide with black fruit.',
       className:'griditem',
    },
    {
      type: 'Perennials',
      title: 'Clematis, Happy Jack Purple',
      description: 'Purple flower with yellow stamens.',
       className:'griditem',
    },
    {
      type: 'Perennials',
      title: 'Clematis, Pink Mink',
      description: 'Pink flower, rebloomer.',
       className:'griditem',
    },
    {
      type: 'Perennials',
      title: 'Clematis, Sweet Summer Love',
      description: 'Cranberry violet flower.',
       className:'griditem',
    },
    {
      type: 'Perennials',
      title: 'Coneflower, Cheyenne Spirit',
      description: 'Shades of orange, red, & yellow.',
       className:'griditem',
    },
    {
      type: 'Perennials',
      title: 'Coneflower, Sombrero Adobe Orange',
      description: '2.5-3in intense orange flowers.',
       className:'griditem',
    },
    {
      type: 'Perennials',
      title: 'Coralbells, Cherry Truffles',
      description: 'Heavily ruffled rich mahogany red foliage.',
       className:'griditem',
    },
    {
      type: 'Perennials',
      title: 'Coralbells, Grape Expectations',
      description: 'Grape foliage with purple veins.',
       className:'griditem',
    },
    {
      type: 'Perennials',
      title: 'Coreopsis, Jethro Tull',
      description: 'Yellow flowers.',
       className:'griditem',
    },
    {
      type: 'Ornamental\/Shade Trees',
      title: 'Crabapple, Coralburst',
      description: 'Coral-pink buds open to double pink flowers.',
       className:'griditem',
    },
    {
      type: 'Ornamental\/Shade Trees',
      title: 'Crabapple, Prairie Fire',
      description: 'Single pink\/red flowers.',
       className:'griditem',
    },
    {
      type: 'Perennials',
      title: 'Dianthus, Black Cherry Frost',
      description: 'Semi-double red flowers with white edges.',
       className:'griditem',
    },
    {
      type: 'Perennials',
      title: 'Dianthus, Cranberry Cocktail',
      description: 'Hot pink flower.',
       className:'griditem',
    },
    {
      type: 'Flowering Shrubs',
      title: 'Dogwood, Bailey's Red Twig',
      description: 'Bright red stems, white flowers, blue berries.',
       className:'griditem',
    },
    {
      type: 'Flowering Shrubs',
      title: 'Dogwood, Variegated',
      description: 'Variegated foliage with bright red winter branches.',
       className:'griditem',
    },
    {
      type: 'Flowering Shrubs',
      title: 'Elderberry, Black Lace',
      description: 'Lacy purple black foliage.',
       className:'griditem',
    },
    {
      type: 'Flowering Shrubs',
      title: 'Elderberry, Lemony Lace',
      description: 'Bright yellow foliage.',
       className:'griditem',
    },
    {
      type: 'Perennials',
      title: 'False Sunflower, Bleeding Hearts',
      description: 'Upright bronze\/green foliage with orange flowers and red centers.',
       className:'griditem',
    },
    {
      type: 'Perennials',
      title: 'False Sunflower, Tuscan Gold',
      description: 'Sunny yellow flowers, compact upright habit.',
       className:'griditem',
    },
    {
      type: 'Perennials',
      title: 'Fern, Ostrich',
      description: 'Vase shaped 3-5' tall lush green fronds.',
       className:'griditem',
    },
    {
      type: 'Small Fruits',
      title: 'Fig, Chicago Hardy',
      description: 'Hardy, self-pollinating, fruits are purple-brown in color.',
       className:'griditem',
    },
    {
      type: 'Flowering Shrubs',
      title: 'Forsythia, Show Off',
      description: 'Abundant large golden flowers.',
       className:'griditem',
    },
    {
      type: 'Perennials',
      title: 'Grass, Red Baron',
      description: 'Upright blades turn cranberry red in summer. Can only sell in Michigan.',
       className:'griditem',
    },
    {
      type: 'Perennials',
      title: 'Grass, Totem Pole',
      description: 'Upright narrow habit. 2.5' wide x 6' tall.',
       className:'griditem',
    },
    {
      type: 'Flowering Shrubs',
      title: 'Honeysuckle, Goldflame',
      description: 'Pink buds to yellow flowers.',
       className:'griditem',
    },
    {
      type: 'Perennials',
      title: 'Hosta, Blue Angel',
      description: 'Grows 4' tall by 4' wide with large blue\/green leaves.',
       className:'griditem',
    },
    {
      type: 'Perennials',
      title: 'Hosta, Frances Williams',
      description: 'Golden yellow edge with green center.',
       className:'griditem',
    },
    {
      type: 'Flowering Shrubs',
      title: 'Hydrangea, Annabelle',
      description: 'Large white blooms.',
       className:'griditem',
    },
    {
      type: 'Flowering Shrubs',
      title: 'Hydrangea, Climbing',
      description: 'Produces white flowers in late June to early July with a slight fragrance.',
       className:'griditem',
    },
    {
      type: 'Flowering Shrubs',
      title: 'Hydrangea, Eclipse',
      description: 'Deep purple foliage with red flowers. Mophead',
       className:'griditem',
    },
    {
      type: 'Flowering Shrubs',
      title: 'Hydrangea, Endless Summer',
      description: 'Blue mophead flower.',
       className:'griditem',
    },
    {
      type: 'Flowering Shrubs',
      title: 'Hydrangea, Endless Summer Bloomstruck',
      description: 'Pink\/blue mophead flower.',
       className:'griditem',
    },
    {
      type: 'Flowering Shrubs',
      title: 'Hydrangea, Endless Summer Summer Crush',
      description: 'Big raspberry red or neon purple blooms. Mophead',
       className:'griditem',
    },
    {
      type: 'Flowering Shrubs',
      title: 'Hydrangea, Fire Light',
      description: 'White flowers that finish rich red.',
       className:'griditem',
    },
    {
      type: 'Flowering Shrubs',
      title: 'Hydrangea, Limelight Prime',
      description: 'Lime green flowers. Improved Limelight.',
       className:'griditem',
    },
    {
      type: 'Ornamental\/Shade Trees',
      title: 'Hydrangea, Little Lime Tree',
      description: 'Flowers open soft green and fade to pink\/burgundy; tree form.',
       className:'griditem',
    },
    {
      type: 'Flowering Shrubs',
      title: 'Hydrangea, Pinky Winky',
      description: 'Two toned flower heads white\/pink.',
       className:'griditem',
    },
    {
      type: 'Ornamental\/Shade Trees',
      title: 'Hydrangea, Pinky Winky Tree',
      description: 'Two toned flower heads white\/pink; tree form.',
       className:'griditem',
    },
    {
      type: 'Flowering Shrubs',
      title: 'Hydrangea, Quick Fire Fab',
      description: 'Early blooming paniculata, large blooms.',
       className:'griditem',
    },
    {
      type: 'Small Fruits',
      title: 'Kiwi, Issai',
      description: 'Self-fertile produces smooth kiwi fruit in fall.',
       className:'griditem',
    },
    {
      type: 'Flowering Shrubs',
      title: 'Lilac, Bloomerang Dark Purple',
      description: 'Reblooming dark purple flowers.',
       className:'griditem',
    },
    {
      type: 'Ornamental\/Shade Trees',
      title: 'Lilac, Bloomerang Dark Purple Tree',
      description: 'Reblooming dark purple flowers; tree form.',
       className:'griditem',
    },
    {
      type: 'Flowering Shrubs',
      title: 'Lilac, Bloomerang Purpink',
      description: 'Rebloomer with pink to purple flowers. 3-5' tall.',
       className:'griditem',
    },
    {
      type: 'Ornamental\/Shade Trees',
      title: 'Maple, Autumn Blaze',
      description: 'Great orange-red fall color.',
       className:'griditem',
    },
    {
      type: 'Ornamental\/Shade Trees',
      title: 'Maple, Crimson King',
      description: 'Dark red leaf color throughout the growing season.',
       className:'griditem',
    },
    {
      type: 'Ornamental\/Shade Trees',
      title: 'Maple, Green Mountain Sugar',
      description: 'Range of yellow to red fall color, good heat tolerance.',
       className:'griditem',
    },
    {
      type: 'Ornamental\/Shade Trees',
      title: 'Maple, October Glory',
      description: 'Fall color is brilliant orange or red.',
       className:'griditem',
    },
    {
      type: 'Ornamental\/Shade Trees',
      title: 'Maple, Red',
      description: 'Foliage turns yellow to bright red in the fall.',
       className:'griditem',
    },
    {
      type: 'Ornamental\/Shade Trees',
      title: 'Maple, Silver',
      description: 'Foliage is bright green with yellowish fall color.',
       className:'griditem',
    },
    {
      type: 'Ornamental\/Shade Trees',
      title: 'Mountain Ash, Cardinal Royal',
      description: 'Bright red fruits in August to September.',
       className:'griditem',
    },
    {
      type: 'Ornamental\/Shade Trees',
      title: 'Ninebark, Diabolo Tree',
      description: 'Stunning deep purple foliage.',
       className:'griditem',
    },
    {
      type: 'Flowering Shrubs',
      title: 'Ninebark, Ginger Wine',
      description: 'Orange\/red to burgundy foliage.',
       className:'griditem',
    },
    {
      type: 'Flowering Shrubs',
      title: 'Ninebark, Summer Wine Black',
      description: 'Very dark foliage, white flowers in spring; 5-6' tall and wide.',
       className:'griditem',
    },
    {
      type: 'Flowering Shrubs',
      title: 'Ninebark, Tiny Wine',
      description: 'Compact form with dark maroon foliage.',
       className:'griditem',
    },
    {
      type: 'Fruit Trees',
      title: 'Peach, Contender',
      description: 'Zone 4 hardiness.',
       className:'griditem',
    },
    {
      type: 'Fruit Trees',
      title: 'Pear, Bartlett',
      description: 'Medium to large yellow fruit with sweet and tender flesh.',
       className:'griditem',
    },
    {
      type: 'Fruit Trees',
      title: 'Pear, Summercrisp',
      description: 'Medium-sized fruit with green skin and crisp sweet flesh.',
       className:'griditem',
    },
    {
      type: 'Perennials',
      title: 'Peony, Bartzella (Yellow)',
      description: 'Intersectional peony with abundant double yellow flowers.',
       className:'griditem',
    },
    {
      type: 'Perennials',
      title: 'Peony, Cora Louise (White\/Lavender)',
      description: 'Large semi-double white flowers with lavender centers.',
       className:'griditem',
    },
    {
      type: 'Perennials',
      title: 'Peony, Coral Charm (Coral)',
      description: 'Early blooming semi double coral flowers.',
       className:'griditem',
    },
    {
      type: 'Perennials',
      title: 'Peony, Sarah Bernhardt (Pink)',
      description: 'Pink flowers.',
       className:'griditem',
    },
    {
      type: 'Perennials',
      title: 'Peony, Victoria de la Marne (Red)',
      description: 'Double red 3-6in flowers in late spring.',
       className:'griditem',
    },
    {
      type: 'Perennials',
      title: 'Phlox, Garden Cover Girl Purple',
      description: 'Lavender purple flowers.',
       className:'griditem',
    },
    {
      type: 'Perennials',
      title: 'Phlox, Garden Glamour Girl',
      description: 'Pink flowers.',
       className:'griditem',
    },
    {
      type: 'Evergreens',
      title: 'Pine, White',
      description: 'Soft, bluish-green needles large specimen tree.',
       className:'griditem',
    },
    {
      type: 'Fruit Trees',
      title: 'Plum, Methley',
      description: 'Small to medium fruit with reddish skin and red flesh.',
       className:'griditem',
    },
    {
      type: 'Fruit Trees',
      title: 'Plum, Stanley',
      description: 'Large dark blue fruits with sweet, greenish-yellow, juicy flesh.',
       className:'griditem',
    },
    {
      type: 'Fruit Trees',
      title: 'Plum, Toka',
      description: 'Large red-skinned fruits with yellow flesh.',
       className:'griditem',
    },
    {
      type: 'Flowering Shrubs',
      title: 'Potentilla, Happy Face Pink Paradise',
      description: 'Clear pink semi-double flowers.',
       className:'griditem',
    },
    {
      type: 'Flowering Shrubs',
      title: 'Potentilla, Happy Face Yellow',
      description: 'Extra-large, bright yellow flowers.',
       className:'griditem',
    },
    {
      type: 'Ornamental\/Shade Trees',
      title: 'Redbud, Eastern Tree Form',
      description: 'Rosy-pink flowers appear on bare branches in spring.',
       className:'griditem',
    },
    {
      type: 'Flowering Shrubs',
      title: 'Rhododendron, PJM Elite',
      description: 'Lavender pink flower and slightly more compact than PJM.',
       className:'griditem',
    },
    {
      type: 'Perennials',
      title: 'Russian Sage',
      description: 'Gray-green foliage and 9-12in long clusters of violet-blue flowers.',
       className:'griditem',
    },
    {
      type: 'Perennials',
      title: 'Salvia, East Friesland',
      description: 'Violet flowers.',
       className:'griditem',
    },
    {
      type: 'Perennials',
      title: 'Salvia, May Night',
      description: 'Dark blue flowers.',
       className:'griditem',
    },
    {
      type: 'Perennials',
      title: 'Sedum, Frosted Fire',
      description: 'Variegated verson of Autumn Fire.',
       className:'griditem',
    },
    {
      type: 'Ornamental\/Shade Trees',
      title: 'Serviceberry, Autumn Brilliance (Tree)',
      description: 'Fall color is yellow to gold, sometimes orange to red.',
       className:'griditem',
    },
    {
      type: 'Ornamental\/Shade Trees',
      title: 'Smoketree, Royal Purple',
      description: 'Velvety purple foliage all season long.',
       className:'griditem',
    },
    {
      type: 'Evergreens',
      title: 'Spruce, Norway',
      description: 'Pyramidal shape and drooping branches, specimen tree.',
       className:'griditem',
    },
    {
      type: 'Flowering Shrubs',
      title: 'St. John's Wort, Gemo',
      description: 'Yellow flowers in summer.',
       className:'griditem',
    },
    {
      type: 'Flowering Shrubs',
      title: 'Summersweet, Ruby Spice',
      description: 'Reddish pink flower in summer.',
       className:'griditem',
    },
    {
      type: 'Ornamental\/Shade Trees',
      title: 'Sycamore, American',
      description: 'Exfoliating tree bark provides unique winter interest.',
       className:'griditem',
    },
    {
      type: 'Perennials',
      title: 'Trumpet Vine, Red',
      description: 'Vigorous vine with 2.5-3in long and 1.5in wide red flowers.',
       className:'griditem',
    },
    {
      type: 'Ornamental\/Shade Trees',
      title: 'Tulip Tree',
      description: 'Foliage is bright green in summer and turns yellow in fall.',
       className:'griditem',
    },
    {
      type: 'Perennials',
      title: 'Veronica, Giles Van Hees Pink',
      description: 'Bright pink flower spikes from mid-summer through late summer.',
       className:'griditem',
    },
    {
      type: 'Perennials',
      title: 'Veronica, Royal Candles',
      description: 'Compact grower with masses of violet blue flowers.',
       className:'griditem',
    },
    {
      type: 'Flowering Shrubs',
      title: 'Viburnum, Common Snowball',
      description: '3in diameter clusters of white flowers.',
       className:'griditem',
    },
    {
      type: 'Flowering Shrubs',
      title: 'Weigela, Midnight Sun',
      description: 'Dwarf with orange-red foliage.',
       className:'griditem',
    },
    {
      type: 'Flowering Shrubs',
      title: 'Weigela, My Monet',
      description: 'Pink\/white\/green variegated foliage.',
       className:'griditem',
    },
    {
      type: 'Flowering Shrubs',
      title: 'Weigela, Sonic Bloom Wine',
      description: 'Rebloomer with dark foliage and pink flowers.',
       className:'griditem',
    },
    {
      type: 'Flowering Shrubs',
      title: 'Weigela, Wine & Roses',
      description: 'Dark burgundy foliage with pink bloom.',
       className:'griditem',
    },
    {
      type: 'Flowering Shrubs',
      title: 'Willow, Dappled',
      description: 'Foliage mottled in white, green and pink.',
       className:'griditem',
    },
    {
      type: 'Flowering Shrubs',
      title: 'Witchhazel, Vernal',
      description: 'Yellow to orange flowers in late winter to early spring.',
       className:'griditem',
    },
  ]
  
separated_data = defaultdict(list)

# Separate the data based on 'type'
for item in data:
    separated_data[item['type']].append(item)

# Save each type to a separate file
for plant_type, items in separated_data.items():
    filename = plant_type.replace("/", "_").replace(" ", "_") + ".json"
    with open(filename, 'w') as f:
        json.dump(items, f, indent=2)

    print(f"Saved {len(items)} items to {filename}")